### ISSUE TITLE
2023-11-22  Open API broken: response for jsonld should be string

### ISSUE THREAD

**Issue by sahalali** [culturecreates/incident-reports#11]
# Incident Report 

## Summary

See https://github.com/culturecreates/footlight-calendar-api/issues/814

### 2023-11-22 

The stringification of json-ld was removed to beautify the response.

### 2023-11-23 

Hotfix deployed into production.

## Lessons learned

Any response change should be communicated and approved by clients before updating. 

### What went well

We were able to do a hotfix within a day of learning about the incident.

### What went wrong

This incident was embarrassing because the client discovered the bug instead of us, and had to inform us of the problem.

### Where we got lucky

We could then fix the issue as soon as the developer's day started.

## Action items

No API response should be changed before approval from clients.

### Process improvements
API response changes should be approved before implmentation.

**Comment by saumier** [comment]
@sahalali Your report looks good. Thx. I will close it.
