### ISSUE TITLE
2024-06-24 Database spike

### ISSUE THREAD

**Issue by saumier** [culturecreates/incident-reports#15]
# Incident Report 

## Summary

Service started to slow to slightly above 1.5 seconds for the Open API calls to list events.  The service gradually grew slower over the next 2 days reaching above 10 seconds at times. Servers were restarted and service returned to normal.

### 2024-06-24 16:00

The incident was opened in Slack channel #footlight-cms after couple of monitoring alerts in Open API were triggered because they took longer than 1.5 seconds to list events.

<img width="888" alt="Screenshot 2024-06-26 at 9 08 23 AM" src="https://github.com/culturecreates/incident-reports/assets/419491/b8c5f555-9365-4a68-9272-e6dcb03754dc">

### 2024-06-26 9:00
The servers where restarted and systems returned to normal.

### Analysis

There was a load spike June 24th that caused production-server-7 to use burst CPU and never fully recover on its own.

The burst from Admin API (not Open API) triggered slow database queries logged at a frequency of 10,000 per second (see graph).

More investigation should be done to find the root cause. At first glance this does **not** seem to be a case of external Open API DOS attack.

<img width="1372" alt="Screenshot 2024-06-26 at 9 24 31 AM" src="https://github.com/culturecreates/incident-reports/assets/419491/13684142-7fcb-49c7-9592-6cac285c7c9b">

Zoom in to sub-section with high burst. There are only 2 Open API requests but hundreds of thousands of mongo db logs. The Admin API requests are also high (see screen grab above).

<img width="1520" alt="Screenshot 2024-06-26 at 9 25 04 AM" src="https://github.com/culturecreates/incident-reports/assets/419491/a3a1c0be-0a27-494b-8c7d-5940f73cd03c">

<img width="762" alt="Screenshot 2024-06-26 at 9 27 23 AM" src="https://github.com/culturecreates/incident-reports/assets/419491/9ff737e6-b3c6-48ed-8206-7f307818acbf">

### What went well

List of things that went well. 

1. We were alerted to the outage by automated bots before it affected users
2. Gregory sounded the alarm in Slack

### What went wrong

Things that could have gone better. Ideally these should result in concrete
action items that have GitHub issues created for them and linked to under
Action items. 

1. We did not fix the problem for 2 days.
2. Gregory is not able to restart the db in production.

### Where we got lucky

These are good things that happened to us but not because we had planned for them.

1. Clients did not formally complain so we think they didn't notice the slow down.

## Action items

These are only sample subheadings. Every action item should have a GitHub issue
(even a small skeleton of one) attached to it, so these do not get forgotten.

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

**Comment by sahalali** [comment]
As a part of my investigation, the following are the action items created:
Action item:
1. Increase the core in the instance. This will require a new instance with 16GB memory and 4 cores.
    Difference in billing: 16GB instance costs USD84/month and 8GB with 2 core costs 44 USD/month
2. Monitor database stats: active connections and active queries next time when CPU usage peaks.
3. Enhancement required on Cache implementation to reduce MongoDB load. Reducing db calls will improve latency.
4. Monitor the service requests daily for potential DOS attacks over the next few days. 

cc @saumier

**Comment by sahalali** [comment]
As a quick response when the servers are not responding, restarting the instance will work from now to automatically restart the services running.
The [doc](https://docs.google.com/document/d/1cybyjjswTXoGaErD5kSYSACRLUXJbt0xJlFRCldJP0c/edit) explains how to restart services and instance.
